// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: nuntio/projects/v1alpha1/projects_project.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectServiceClient interface {
	// Ping returns an empty response used to check if the server is live
	Ping(ctx context.Context, in *ProjectServicePingRequest, opts ...grpc.CallOption) (*ProjectServicePingResponse, error)
	// Create initializes a new project and all relating ressources
	Create(ctx context.Context, in *ProjectServiceCreateRequest, opts ...grpc.CallOption) (*ProjectServiceCreateResponse, error)
	// Deletes deletes a project and all its ressources
	Delete(ctx context.Context, in *ProjectServiceDeleteRequest, opts ...grpc.CallOption) (*ProjectServiceDeleteResponse, error)
	// Update updates a project with a new name, logo etc.
	Update(ctx context.Context, in *ProjectServiceUpdateRequest, opts ...grpc.CallOption) (*ProjectServiceUpdateResponse, error)
	// Get fetches a speicfic project
	Get(ctx context.Context, in *ProjectServiceGetRequest, opts ...grpc.CallOption) (*ProjectServiceGetResponse, error)
	// List returns a list of projects
	List(ctx context.Context, in *ProjectServiceListRequest, opts ...grpc.CallOption) (*ProjectServiceListResponse, error)
	// Enables storage for the project
	EnableStorage(ctx context.Context, in *ProjectServiceEnableStorageRequest, opts ...grpc.CallOption) (*ProjectServiceEnableStorageResponse, error)
	// Disables storage for the project
	DisableStorage(ctx context.Context, in *ProjectServiceDisableStorageRequest, opts ...grpc.CallOption) (*ProjectServiceDisableStorageResponse, error)
	// Enables USers for the project
	EnableUsers(ctx context.Context, in *ProjectServiceEnableUsersRequest, opts ...grpc.CallOption) (*ProjectServiceEnableUsersResponse, error)
	// Disables Users for the project
	DisableUsers(ctx context.Context, in *ProjectServiceDisableUsersRequest, opts ...grpc.CallOption) (*ProjectServiceDisableUsersResponse, error)
	// Enables Mongo for the project
	EnableMongo(ctx context.Context, in *ProjectServiceEnableMongoRequest, opts ...grpc.CallOption) (*ProjectServiceEnableMongoResponse, error)
	// Disables Mongo for the project
	DisableMongo(ctx context.Context, in *ProjectServiceDisableMongoRequest, opts ...grpc.CallOption) (*ProjectServiceDisableMongoResponse, error)
	// Enables Postgres for the project
	EnablePostgres(ctx context.Context, in *ProjectServiceEnablePostgresRequest, opts ...grpc.CallOption) (*ProjectServiceEnablePostgresResponse, error)
	// Disable Postgres for the project
	DisablePostgres(ctx context.Context, in *ProjectServiceDisablePostgresRequest, opts ...grpc.CallOption) (*ProjectServiceDisablePostgresResponse, error)
}

type projectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectServiceClient(cc grpc.ClientConnInterface) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) Ping(ctx context.Context, in *ProjectServicePingRequest, opts ...grpc.CallOption) (*ProjectServicePingResponse, error) {
	out := new(ProjectServicePingResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Create(ctx context.Context, in *ProjectServiceCreateRequest, opts ...grpc.CallOption) (*ProjectServiceCreateResponse, error) {
	out := new(ProjectServiceCreateResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Delete(ctx context.Context, in *ProjectServiceDeleteRequest, opts ...grpc.CallOption) (*ProjectServiceDeleteResponse, error) {
	out := new(ProjectServiceDeleteResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Update(ctx context.Context, in *ProjectServiceUpdateRequest, opts ...grpc.CallOption) (*ProjectServiceUpdateResponse, error) {
	out := new(ProjectServiceUpdateResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Get(ctx context.Context, in *ProjectServiceGetRequest, opts ...grpc.CallOption) (*ProjectServiceGetResponse, error) {
	out := new(ProjectServiceGetResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) List(ctx context.Context, in *ProjectServiceListRequest, opts ...grpc.CallOption) (*ProjectServiceListResponse, error) {
	out := new(ProjectServiceListResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) EnableStorage(ctx context.Context, in *ProjectServiceEnableStorageRequest, opts ...grpc.CallOption) (*ProjectServiceEnableStorageResponse, error) {
	out := new(ProjectServiceEnableStorageResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectService/EnableStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) DisableStorage(ctx context.Context, in *ProjectServiceDisableStorageRequest, opts ...grpc.CallOption) (*ProjectServiceDisableStorageResponse, error) {
	out := new(ProjectServiceDisableStorageResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectService/DisableStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) EnableUsers(ctx context.Context, in *ProjectServiceEnableUsersRequest, opts ...grpc.CallOption) (*ProjectServiceEnableUsersResponse, error) {
	out := new(ProjectServiceEnableUsersResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectService/EnableUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) DisableUsers(ctx context.Context, in *ProjectServiceDisableUsersRequest, opts ...grpc.CallOption) (*ProjectServiceDisableUsersResponse, error) {
	out := new(ProjectServiceDisableUsersResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectService/DisableUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) EnableMongo(ctx context.Context, in *ProjectServiceEnableMongoRequest, opts ...grpc.CallOption) (*ProjectServiceEnableMongoResponse, error) {
	out := new(ProjectServiceEnableMongoResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectService/EnableMongo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) DisableMongo(ctx context.Context, in *ProjectServiceDisableMongoRequest, opts ...grpc.CallOption) (*ProjectServiceDisableMongoResponse, error) {
	out := new(ProjectServiceDisableMongoResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectService/DisableMongo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) EnablePostgres(ctx context.Context, in *ProjectServiceEnablePostgresRequest, opts ...grpc.CallOption) (*ProjectServiceEnablePostgresResponse, error) {
	out := new(ProjectServiceEnablePostgresResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectService/EnablePostgres", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) DisablePostgres(ctx context.Context, in *ProjectServiceDisablePostgresRequest, opts ...grpc.CallOption) (*ProjectServiceDisablePostgresResponse, error) {
	out := new(ProjectServiceDisablePostgresResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectService/DisablePostgres", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
// All implementations should embed UnimplementedProjectServiceServer
// for forward compatibility
type ProjectServiceServer interface {
	// Ping returns an empty response used to check if the server is live
	Ping(context.Context, *ProjectServicePingRequest) (*ProjectServicePingResponse, error)
	// Create initializes a new project and all relating ressources
	Create(context.Context, *ProjectServiceCreateRequest) (*ProjectServiceCreateResponse, error)
	// Deletes deletes a project and all its ressources
	Delete(context.Context, *ProjectServiceDeleteRequest) (*ProjectServiceDeleteResponse, error)
	// Update updates a project with a new name, logo etc.
	Update(context.Context, *ProjectServiceUpdateRequest) (*ProjectServiceUpdateResponse, error)
	// Get fetches a speicfic project
	Get(context.Context, *ProjectServiceGetRequest) (*ProjectServiceGetResponse, error)
	// List returns a list of projects
	List(context.Context, *ProjectServiceListRequest) (*ProjectServiceListResponse, error)
	// Enables storage for the project
	EnableStorage(context.Context, *ProjectServiceEnableStorageRequest) (*ProjectServiceEnableStorageResponse, error)
	// Disables storage for the project
	DisableStorage(context.Context, *ProjectServiceDisableStorageRequest) (*ProjectServiceDisableStorageResponse, error)
	// Enables USers for the project
	EnableUsers(context.Context, *ProjectServiceEnableUsersRequest) (*ProjectServiceEnableUsersResponse, error)
	// Disables Users for the project
	DisableUsers(context.Context, *ProjectServiceDisableUsersRequest) (*ProjectServiceDisableUsersResponse, error)
	// Enables Mongo for the project
	EnableMongo(context.Context, *ProjectServiceEnableMongoRequest) (*ProjectServiceEnableMongoResponse, error)
	// Disables Mongo for the project
	DisableMongo(context.Context, *ProjectServiceDisableMongoRequest) (*ProjectServiceDisableMongoResponse, error)
	// Enables Postgres for the project
	EnablePostgres(context.Context, *ProjectServiceEnablePostgresRequest) (*ProjectServiceEnablePostgresResponse, error)
	// Disable Postgres for the project
	DisablePostgres(context.Context, *ProjectServiceDisablePostgresRequest) (*ProjectServiceDisablePostgresResponse, error)
}

// UnimplementedProjectServiceServer should be embedded to have forward compatible implementations.
type UnimplementedProjectServiceServer struct {
}

func (UnimplementedProjectServiceServer) Ping(context.Context, *ProjectServicePingRequest) (*ProjectServicePingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedProjectServiceServer) Create(context.Context, *ProjectServiceCreateRequest) (*ProjectServiceCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedProjectServiceServer) Delete(context.Context, *ProjectServiceDeleteRequest) (*ProjectServiceDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedProjectServiceServer) Update(context.Context, *ProjectServiceUpdateRequest) (*ProjectServiceUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedProjectServiceServer) Get(context.Context, *ProjectServiceGetRequest) (*ProjectServiceGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedProjectServiceServer) List(context.Context, *ProjectServiceListRequest) (*ProjectServiceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedProjectServiceServer) EnableStorage(context.Context, *ProjectServiceEnableStorageRequest) (*ProjectServiceEnableStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableStorage not implemented")
}
func (UnimplementedProjectServiceServer) DisableStorage(context.Context, *ProjectServiceDisableStorageRequest) (*ProjectServiceDisableStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableStorage not implemented")
}
func (UnimplementedProjectServiceServer) EnableUsers(context.Context, *ProjectServiceEnableUsersRequest) (*ProjectServiceEnableUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableUsers not implemented")
}
func (UnimplementedProjectServiceServer) DisableUsers(context.Context, *ProjectServiceDisableUsersRequest) (*ProjectServiceDisableUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableUsers not implemented")
}
func (UnimplementedProjectServiceServer) EnableMongo(context.Context, *ProjectServiceEnableMongoRequest) (*ProjectServiceEnableMongoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableMongo not implemented")
}
func (UnimplementedProjectServiceServer) DisableMongo(context.Context, *ProjectServiceDisableMongoRequest) (*ProjectServiceDisableMongoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableMongo not implemented")
}
func (UnimplementedProjectServiceServer) EnablePostgres(context.Context, *ProjectServiceEnablePostgresRequest) (*ProjectServiceEnablePostgresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnablePostgres not implemented")
}
func (UnimplementedProjectServiceServer) DisablePostgres(context.Context, *ProjectServiceDisablePostgresRequest) (*ProjectServiceDisablePostgresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisablePostgres not implemented")
}

// UnsafeProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectServiceServer will
// result in compilation errors.
type UnsafeProjectServiceServer interface {
	mustEmbedUnimplementedProjectServiceServer()
}

func RegisterProjectServiceServer(s grpc.ServiceRegistrar, srv ProjectServiceServer) {
	s.RegisterService(&ProjectService_ServiceDesc, srv)
}

func _ProjectService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServicePingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Ping(ctx, req.(*ProjectServicePingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Create(ctx, req.(*ProjectServiceCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Delete(ctx, req.(*ProjectServiceDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Update(ctx, req.(*ProjectServiceUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Get(ctx, req.(*ProjectServiceGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).List(ctx, req.(*ProjectServiceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_EnableStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceEnableStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).EnableStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectService/EnableStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).EnableStorage(ctx, req.(*ProjectServiceEnableStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_DisableStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceDisableStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).DisableStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectService/DisableStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).DisableStorage(ctx, req.(*ProjectServiceDisableStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_EnableUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceEnableUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).EnableUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectService/EnableUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).EnableUsers(ctx, req.(*ProjectServiceEnableUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_DisableUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceDisableUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).DisableUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectService/DisableUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).DisableUsers(ctx, req.(*ProjectServiceDisableUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_EnableMongo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceEnableMongoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).EnableMongo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectService/EnableMongo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).EnableMongo(ctx, req.(*ProjectServiceEnableMongoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_DisableMongo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceDisableMongoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).DisableMongo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectService/DisableMongo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).DisableMongo(ctx, req.(*ProjectServiceDisableMongoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_EnablePostgres_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceEnablePostgresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).EnablePostgres(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectService/EnablePostgres",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).EnablePostgres(ctx, req.(*ProjectServiceEnablePostgresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_DisablePostgres_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceDisablePostgresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).DisablePostgres(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectService/DisablePostgres",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).DisablePostgres(ctx, req.(*ProjectServiceDisablePostgresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectService_ServiceDesc is the grpc.ServiceDesc for ProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nuntio.projects.v1alpha1.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ProjectService_Ping_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ProjectService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProjectService_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProjectService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ProjectService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ProjectService_List_Handler,
		},
		{
			MethodName: "EnableStorage",
			Handler:    _ProjectService_EnableStorage_Handler,
		},
		{
			MethodName: "DisableStorage",
			Handler:    _ProjectService_DisableStorage_Handler,
		},
		{
			MethodName: "EnableUsers",
			Handler:    _ProjectService_EnableUsers_Handler,
		},
		{
			MethodName: "DisableUsers",
			Handler:    _ProjectService_DisableUsers_Handler,
		},
		{
			MethodName: "EnableMongo",
			Handler:    _ProjectService_EnableMongo_Handler,
		},
		{
			MethodName: "DisableMongo",
			Handler:    _ProjectService_DisableMongo_Handler,
		},
		{
			MethodName: "EnablePostgres",
			Handler:    _ProjectService_EnablePostgres_Handler,
		},
		{
			MethodName: "DisablePostgres",
			Handler:    _ProjectService_DisablePostgres_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nuntio/projects/v1alpha1/projects_project.proto",
}
