// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: nuntio/projects/v1alpha1/projects_projects.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProjectsServiceClient is the client API for ProjectsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectsServiceClient interface {
	// Ping returns an empty response used to check if the server is live
	Ping(ctx context.Context, in *ProjectServicePingRequest, opts ...grpc.CallOption) (*ProjectServicePingResponse, error)
	// Create initializes a new project and all relating ressources
	Create(ctx context.Context, in *ProjectServiceCreateRequest, opts ...grpc.CallOption) (*ProjectServiceCreateResponse, error)
	// Deletes deletes a project and all its ressources
	Delete(ctx context.Context, in *ProjectServiceDeleteRequest, opts ...grpc.CallOption) (*ProjectServiceDeleteResponse, error)
	// Update updates a project with a new name, logo etc.
	Update(ctx context.Context, in *ProjectServiceUpdateRequest, opts ...grpc.CallOption) (*ProjectServiceUpdateResponse, error)
	// Get fetches a speicfic project
	Get(ctx context.Context, in *ProjectServiceGetRequest, opts ...grpc.CallOption) (*ProjectServiceGetResponse, error)
	// List returns a list of projects
	List(ctx context.Context, in *ProjectServiceListRequest, opts ...grpc.CallOption) (*ProjectServiceListResponse, error)
	// Enables storage for the project
	EnableStorage(ctx context.Context, in *ProjectServiceEnableStorageRequest, opts ...grpc.CallOption) (*ProjectServiceEnableStorageResponse, error)
	// Disables storage for the project
	DisableStorage(ctx context.Context, in *ProjectServiceDisableStorageRequest, opts ...grpc.CallOption) (*ProjectServiceDisableStorageResponse, error)
	// Enables USers for the project
	EnableUsers(ctx context.Context, in *ProjectServiceEnableUsersRequest, opts ...grpc.CallOption) (*ProjectServiceEnableUsersResponse, error)
	// Disables Users for the project
	DisableUsers(ctx context.Context, in *ProjectServiceDisableUsersRequest, opts ...grpc.CallOption) (*ProjectServiceDisableUsersResponse, error)
	// Enables Mongo for the project
	EnableMongo(ctx context.Context, in *ProjectServiceEnableMongoRequest, opts ...grpc.CallOption) (*ProjectServiceEnableMongoResponse, error)
	// Disables Mongo for the project
	DisableMongo(ctx context.Context, in *ProjectServiceDisableMongoRequest, opts ...grpc.CallOption) (*ProjectServiceDisableMongoResponse, error)
	// Enables Postgres for the project
	EnablePostgres(ctx context.Context, in *ProjectServiceEnablePostgresRequest, opts ...grpc.CallOption) (*ProjectServiceEnablePostgresResponse, error)
	// Disable Postgres for the project
	DisablePostgres(ctx context.Context, in *ProjectServiceDisablePostgresRequest, opts ...grpc.CallOption) (*ProjectServiceDisablePostgresResponse, error)
}

type projectsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectsServiceClient(cc grpc.ClientConnInterface) ProjectsServiceClient {
	return &projectsServiceClient{cc}
}

func (c *projectsServiceClient) Ping(ctx context.Context, in *ProjectServicePingRequest, opts ...grpc.CallOption) (*ProjectServicePingResponse, error) {
	out := new(ProjectServicePingResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectsService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) Create(ctx context.Context, in *ProjectServiceCreateRequest, opts ...grpc.CallOption) (*ProjectServiceCreateResponse, error) {
	out := new(ProjectServiceCreateResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectsService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) Delete(ctx context.Context, in *ProjectServiceDeleteRequest, opts ...grpc.CallOption) (*ProjectServiceDeleteResponse, error) {
	out := new(ProjectServiceDeleteResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectsService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) Update(ctx context.Context, in *ProjectServiceUpdateRequest, opts ...grpc.CallOption) (*ProjectServiceUpdateResponse, error) {
	out := new(ProjectServiceUpdateResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectsService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) Get(ctx context.Context, in *ProjectServiceGetRequest, opts ...grpc.CallOption) (*ProjectServiceGetResponse, error) {
	out := new(ProjectServiceGetResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectsService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) List(ctx context.Context, in *ProjectServiceListRequest, opts ...grpc.CallOption) (*ProjectServiceListResponse, error) {
	out := new(ProjectServiceListResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectsService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) EnableStorage(ctx context.Context, in *ProjectServiceEnableStorageRequest, opts ...grpc.CallOption) (*ProjectServiceEnableStorageResponse, error) {
	out := new(ProjectServiceEnableStorageResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectsService/EnableStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) DisableStorage(ctx context.Context, in *ProjectServiceDisableStorageRequest, opts ...grpc.CallOption) (*ProjectServiceDisableStorageResponse, error) {
	out := new(ProjectServiceDisableStorageResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectsService/DisableStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) EnableUsers(ctx context.Context, in *ProjectServiceEnableUsersRequest, opts ...grpc.CallOption) (*ProjectServiceEnableUsersResponse, error) {
	out := new(ProjectServiceEnableUsersResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectsService/EnableUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) DisableUsers(ctx context.Context, in *ProjectServiceDisableUsersRequest, opts ...grpc.CallOption) (*ProjectServiceDisableUsersResponse, error) {
	out := new(ProjectServiceDisableUsersResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectsService/DisableUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) EnableMongo(ctx context.Context, in *ProjectServiceEnableMongoRequest, opts ...grpc.CallOption) (*ProjectServiceEnableMongoResponse, error) {
	out := new(ProjectServiceEnableMongoResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectsService/EnableMongo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) DisableMongo(ctx context.Context, in *ProjectServiceDisableMongoRequest, opts ...grpc.CallOption) (*ProjectServiceDisableMongoResponse, error) {
	out := new(ProjectServiceDisableMongoResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectsService/DisableMongo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) EnablePostgres(ctx context.Context, in *ProjectServiceEnablePostgresRequest, opts ...grpc.CallOption) (*ProjectServiceEnablePostgresResponse, error) {
	out := new(ProjectServiceEnablePostgresResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectsService/EnablePostgres", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) DisablePostgres(ctx context.Context, in *ProjectServiceDisablePostgresRequest, opts ...grpc.CallOption) (*ProjectServiceDisablePostgresResponse, error) {
	out := new(ProjectServiceDisablePostgresResponse)
	err := c.cc.Invoke(ctx, "/nuntio.projects.v1alpha1.ProjectsService/DisablePostgres", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectsServiceServer is the server API for ProjectsService service.
// All implementations should embed UnimplementedProjectsServiceServer
// for forward compatibility
type ProjectsServiceServer interface {
	// Ping returns an empty response used to check if the server is live
	Ping(context.Context, *ProjectServicePingRequest) (*ProjectServicePingResponse, error)
	// Create initializes a new project and all relating ressources
	Create(context.Context, *ProjectServiceCreateRequest) (*ProjectServiceCreateResponse, error)
	// Deletes deletes a project and all its ressources
	Delete(context.Context, *ProjectServiceDeleteRequest) (*ProjectServiceDeleteResponse, error)
	// Update updates a project with a new name, logo etc.
	Update(context.Context, *ProjectServiceUpdateRequest) (*ProjectServiceUpdateResponse, error)
	// Get fetches a speicfic project
	Get(context.Context, *ProjectServiceGetRequest) (*ProjectServiceGetResponse, error)
	// List returns a list of projects
	List(context.Context, *ProjectServiceListRequest) (*ProjectServiceListResponse, error)
	// Enables storage for the project
	EnableStorage(context.Context, *ProjectServiceEnableStorageRequest) (*ProjectServiceEnableStorageResponse, error)
	// Disables storage for the project
	DisableStorage(context.Context, *ProjectServiceDisableStorageRequest) (*ProjectServiceDisableStorageResponse, error)
	// Enables USers for the project
	EnableUsers(context.Context, *ProjectServiceEnableUsersRequest) (*ProjectServiceEnableUsersResponse, error)
	// Disables Users for the project
	DisableUsers(context.Context, *ProjectServiceDisableUsersRequest) (*ProjectServiceDisableUsersResponse, error)
	// Enables Mongo for the project
	EnableMongo(context.Context, *ProjectServiceEnableMongoRequest) (*ProjectServiceEnableMongoResponse, error)
	// Disables Mongo for the project
	DisableMongo(context.Context, *ProjectServiceDisableMongoRequest) (*ProjectServiceDisableMongoResponse, error)
	// Enables Postgres for the project
	EnablePostgres(context.Context, *ProjectServiceEnablePostgresRequest) (*ProjectServiceEnablePostgresResponse, error)
	// Disable Postgres for the project
	DisablePostgres(context.Context, *ProjectServiceDisablePostgresRequest) (*ProjectServiceDisablePostgresResponse, error)
}

// UnimplementedProjectsServiceServer should be embedded to have forward compatible implementations.
type UnimplementedProjectsServiceServer struct {
}

func (UnimplementedProjectsServiceServer) Ping(context.Context, *ProjectServicePingRequest) (*ProjectServicePingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedProjectsServiceServer) Create(context.Context, *ProjectServiceCreateRequest) (*ProjectServiceCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedProjectsServiceServer) Delete(context.Context, *ProjectServiceDeleteRequest) (*ProjectServiceDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedProjectsServiceServer) Update(context.Context, *ProjectServiceUpdateRequest) (*ProjectServiceUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedProjectsServiceServer) Get(context.Context, *ProjectServiceGetRequest) (*ProjectServiceGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedProjectsServiceServer) List(context.Context, *ProjectServiceListRequest) (*ProjectServiceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedProjectsServiceServer) EnableStorage(context.Context, *ProjectServiceEnableStorageRequest) (*ProjectServiceEnableStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableStorage not implemented")
}
func (UnimplementedProjectsServiceServer) DisableStorage(context.Context, *ProjectServiceDisableStorageRequest) (*ProjectServiceDisableStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableStorage not implemented")
}
func (UnimplementedProjectsServiceServer) EnableUsers(context.Context, *ProjectServiceEnableUsersRequest) (*ProjectServiceEnableUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableUsers not implemented")
}
func (UnimplementedProjectsServiceServer) DisableUsers(context.Context, *ProjectServiceDisableUsersRequest) (*ProjectServiceDisableUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableUsers not implemented")
}
func (UnimplementedProjectsServiceServer) EnableMongo(context.Context, *ProjectServiceEnableMongoRequest) (*ProjectServiceEnableMongoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableMongo not implemented")
}
func (UnimplementedProjectsServiceServer) DisableMongo(context.Context, *ProjectServiceDisableMongoRequest) (*ProjectServiceDisableMongoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableMongo not implemented")
}
func (UnimplementedProjectsServiceServer) EnablePostgres(context.Context, *ProjectServiceEnablePostgresRequest) (*ProjectServiceEnablePostgresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnablePostgres not implemented")
}
func (UnimplementedProjectsServiceServer) DisablePostgres(context.Context, *ProjectServiceDisablePostgresRequest) (*ProjectServiceDisablePostgresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisablePostgres not implemented")
}

// UnsafeProjectsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectsServiceServer will
// result in compilation errors.
type UnsafeProjectsServiceServer interface {
	mustEmbedUnimplementedProjectsServiceServer()
}

func RegisterProjectsServiceServer(s grpc.ServiceRegistrar, srv ProjectsServiceServer) {
	s.RegisterService(&ProjectsService_ServiceDesc, srv)
}

func _ProjectsService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServicePingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectsService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).Ping(ctx, req.(*ProjectServicePingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectsService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).Create(ctx, req.(*ProjectServiceCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectsService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).Delete(ctx, req.(*ProjectServiceDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectsService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).Update(ctx, req.(*ProjectServiceUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectsService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).Get(ctx, req.(*ProjectServiceGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectsService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).List(ctx, req.(*ProjectServiceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_EnableStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceEnableStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).EnableStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectsService/EnableStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).EnableStorage(ctx, req.(*ProjectServiceEnableStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_DisableStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceDisableStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).DisableStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectsService/DisableStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).DisableStorage(ctx, req.(*ProjectServiceDisableStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_EnableUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceEnableUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).EnableUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectsService/EnableUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).EnableUsers(ctx, req.(*ProjectServiceEnableUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_DisableUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceDisableUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).DisableUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectsService/DisableUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).DisableUsers(ctx, req.(*ProjectServiceDisableUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_EnableMongo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceEnableMongoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).EnableMongo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectsService/EnableMongo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).EnableMongo(ctx, req.(*ProjectServiceEnableMongoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_DisableMongo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceDisableMongoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).DisableMongo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectsService/DisableMongo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).DisableMongo(ctx, req.(*ProjectServiceDisableMongoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_EnablePostgres_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceEnablePostgresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).EnablePostgres(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectsService/EnablePostgres",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).EnablePostgres(ctx, req.(*ProjectServiceEnablePostgresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_DisablePostgres_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectServiceDisablePostgresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).DisablePostgres(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nuntio.projects.v1alpha1.ProjectsService/DisablePostgres",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).DisablePostgres(ctx, req.(*ProjectServiceDisablePostgresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectsService_ServiceDesc is the grpc.ServiceDesc for ProjectsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nuntio.projects.v1alpha1.ProjectsService",
	HandlerType: (*ProjectsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ProjectsService_Ping_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ProjectsService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProjectsService_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProjectsService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ProjectsService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ProjectsService_List_Handler,
		},
		{
			MethodName: "EnableStorage",
			Handler:    _ProjectsService_EnableStorage_Handler,
		},
		{
			MethodName: "DisableStorage",
			Handler:    _ProjectsService_DisableStorage_Handler,
		},
		{
			MethodName: "EnableUsers",
			Handler:    _ProjectsService_EnableUsers_Handler,
		},
		{
			MethodName: "DisableUsers",
			Handler:    _ProjectsService_DisableUsers_Handler,
		},
		{
			MethodName: "EnableMongo",
			Handler:    _ProjectsService_EnableMongo_Handler,
		},
		{
			MethodName: "DisableMongo",
			Handler:    _ProjectsService_DisableMongo_Handler,
		},
		{
			MethodName: "EnablePostgres",
			Handler:    _ProjectsService_EnablePostgres_Handler,
		},
		{
			MethodName: "DisablePostgres",
			Handler:    _ProjectsService_DisablePostgres_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nuntio/projects/v1alpha1/projects_projects.proto",
}
