name: Build and push image to Buf.Build

on:
  push:
    branches: [main]

jobs:
  setup-build-publish-deploy:
    name: Publish to Buf
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      # BUILD BUF (gRPC/PROTOBUF)
      - uses: bufbuild/buf-setup-action@v1
        with:
          buf_user: ${{ secrets.BUF_USER }}
          buf_api_token: ${{ secrets.BUF_TOKEN }}
      
      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}